import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import pugPlugin from 'vite-plugin-pug'
import ui from '@nuxt/ui/vite'
import type { Plugin } from 'vite'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { expressDevPlugin } from './express-server'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/**
 * GitHub Pages serves the site under `/jsonforms_builder/`. The playground SPA
 * lives at `/jsonforms_builder/play/` (copied into `docs/public/play`) so it does
 * not collide with the VitePress page `/playground`.
 * Local `yarn start:dev` keeps `base: '/'`.
 */
const playgroundBase = process.env.PLAYGROUND_BASE ?? '/'

/**
 * Stub for `#build/nuxt-icon-client-bundle`.
 *
 * `UIcon` relies on `@nuxt/icon`, whose runtime imports a module generated by the
 * *Nuxt module* — which does not exist in pure Vue mode. Without this stub, any page
 * using an icon (hence the slightest `UButton`) fails at resolution.
 *
 * The client bundle is meant to embed icons offline; here they are loaded on demand
 * by `@iconify/vue`, so an empty `init` is enough.
 */
function nuxtIconVueShims(): Plugin {
  const BUNDLE = '\0virtual:nuxt-icon-client-bundle'
  const IMPORTS = '\0virtual:playground-imports'

  return {
    name: 'playground:nuxt-icon-vue-shims',
    enforce: 'pre',
    resolveId(id) {
      if (id === '#build/nuxt-icon-client-bundle') return BUNDLE
      if (id === '#imports') return IMPORTS
    },
    load(id) {
      // The client bundle is meant to embed icons offline; here they are
      // loaded on demand by `@iconify/vue`, so an empty `init` is enough.
      if (id === BUNDLE) {
        return 'export function init() {}'
      }

      /*
       * `#imports`: reuse Nuxt UI's stub and add the four symbols `@nuxt/icon`
       * also expects (`onServerPrefetch`, `defineComponent`, `useAsyncData`,
       * `useRequestFetch`). The playground being a client SPA, the degraded
       * versions are enough.
       */
      if (id === IMPORTS) {
        return `
export * from '@nuxt/ui/runtime/vue/stubs/base.js'
export { defineComponent, onServerPrefetch } from 'vue'
export const useRequestFetch = () => globalThis.$fetch ?? fetch
export const useAsyncData = async (_key, handler) => {
  const data = await handler()
  return { data: { value: data }, error: { value: null }, pending: { value: false } }
}
`
      }
    },
  }
}

export default defineConfig({
  base: playgroundBase,
  plugins: [
    nuxtIconVueShims(),
    // `ui()` first: it sets `optimizeDeps.exclude` on `@nuxt/ui` (required for Vite
    // to resolve `#build/ui/*` and `#imports`) and installs `U*` auto-imports.
    // `colorMode` mounts the light/dark theme plugin outside Nuxt.
    ui({
      colorMode: true,
      ui: {
        colors: {
          primary: 'brand',
          neutral: 'slate',
        },
        // Form-density editor: Nuxt UI defaults to article prose (`*:my-5`, `sm:px-8`).
        editor: {
          slots: {
            base: (defaults: string) =>
              String(defaults ?? '')
                .replaceAll('*:my-5', '*:my-1')
                .replaceAll('sm:px-8', '')
                .replace(/\s+/g, ' ')
                .trim(),
          },
        },
      },
    }),
    vue(),
    pugPlugin({
      pretty: true,
    }),
    expressDevPlugin(),
  ],

  build: {
    outDir: path.resolve(__dirname, '../docs/public/play'),
    emptyOutDir: true,
  },

  optimizeDeps: {
    /*
     * Nuxt UI excludes itself from pre-bundling, but not `@nuxt/icon`: its runtime
     * files import the `#imports` alias, which only Nuxt UI's Vite plugin can
     * resolve — and the esbuild pre-bundler runs outside that pipeline.
     */
    exclude: ['@nuxt/ui', '@nuxt/icon'],
  },

  resolve: {
    /*
     * ProseMirror identifies its plugins by object identity: two copies of
     * `prosemirror-state` in the dependency tree and `UEditor` throws
     * « Adding different instances of a keyed plugin (plugin$) ».
     *
     * Package managers easily install several versions (here 1.4.3 under
     * `prosemirror-keymap` and 1.4.4 at the root), hence this explicit
     * deduplication. Reproduce on the host app if it uses the WYSIWYG renderer.
     */
    dedupe: [
      'vue',
      '@tiptap/core',
      '@tiptap/pm',
      '@tiptap/vue-3',
      'prosemirror-state',
      'prosemirror-view',
      'prosemirror-model',
      'prosemirror-transform',
      'prosemirror-keymap',
      'prosemirror-commands',
    ],
  },
})
