import { readdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Plugin, PluginOption } from 'vite'
import ui from '@nuxt/ui/vite'
import pugPlugin from 'vite-plugin-pug'
import { expressDevPlugin } from './express-server'

/**
 * Stub for `#build/nuxt-icon-client-bundle` / `#imports`.
 *
 * `UIcon` relies on `@nuxt/icon`, whose runtime imports a module generated by the
 * Nuxt module — which does not exist in pure Vue / VitePress. Without this stub,
 * any page using an icon fails at resolution.
 *
 * Do **not** stub `#build/app.config`: `@nuxt/ui/vite` already provides
 * `virtual:nuxt-ui-app-config` with `ui.colors`. An empty stub made
 * `appConfig.ui.colors` crash at mount (`Cannot read properties of undefined`).
 */
export function nuxtIconVueShims(): Plugin {
  const BUNDLE = '\0virtual:nuxt-icon-client-bundle'
  const IMPORTS = '\0virtual:playground-imports'

  return {
    name: 'playground:nuxt-icon-vue-shims',
    enforce: 'pre',
    resolveId(id) {
      if (id === '#build/nuxt-icon-client-bundle') return BUNDLE
      if (id === '#imports') return IMPORTS
    },
    load(id) {
      if (id === BUNDLE) {
        return 'export function init() {}'
      }

      if (id === IMPORTS) {
        return `
export * from '@nuxt/ui/runtime/vue/stubs/base.js'
export { defineComponent, onServerPrefetch } from 'vue'
export const useRequestFetch = () => globalThis.$fetch ?? fetch
export const useAsyncData = async (_key, handler) => {
  const data = await handler()
  return { data: { value: data }, error: { value: null }, pending: { value: false } }
}
`
      }
    },
  }
}

/** Shared Nuxt UI + Pug + icon shims for the standalone playground and VitePress. */
export const playgroundUiPlugins = (options?: {
  /** Start the mock `/api/*` Express server (dev only). Default: true. */
  express?: boolean
}): PluginOption[] => {
  const plugins: PluginOption[] = [
    nuxtIconVueShims(),
    // `ui()` first relative to Vue consumers: sets `optimizeDeps.exclude` on `@nuxt/ui`
    // and installs `U*` auto-imports.
    ui({
      colorMode: true,
      ui: {
        colors: {
          primary: 'brand',
          neutral: 'slate',
        },
        editor: {
          slots: {
            base: (defaults: string) =>
              String(defaults ?? '')
                .replaceAll('*:my-5', '*:my-1')
                .replaceAll('sm:px-8', '')
                .replace(/\s+/g, ' ')
                .trim(),
          },
        },
      },
    }),
    pugPlugin({
      pretty: true,
    }),
  ]

  if (options?.express !== false) {
    plugins.push(expressDevPlugin())
  }

  return plugins
}

export const playgroundResolveDedupe = [
  'vue',
  '@tiptap/core',
  '@tiptap/pm',
  '@tiptap/vue-3',
  'prosemirror-state',
  'prosemirror-view',
  'prosemirror-model',
  'prosemirror-transform',
  'prosemirror-keymap',
  'prosemirror-commands',
] as const

/**
 * Every installed `@tiptap/*` + `prosemirror-*` package, to hand to
 * `optimizeDeps.exclude`.
 *
 * `dedupe` alone is not enough. `@nuxt/ui` must stay excluded from pre-bundling
 * (its runtime imports `#imports`, which esbuild cannot resolve), and Vite never
 * scans inside an excluded dep — so the packages Nuxt UI's `Editor.vue` pulls in
 * (`@tiptap/starter-kit`, `@tiptap/markdown`, `extension-code`…) stay raw source
 * while the ones our own `src/advanced/*` imports (`@tiptap/core`, `@tiptap/vue-3`)
 * get pre-bundled. Two copies of `prosemirror-state`, and `new Editor()` throws
 * « Adding different instances of a keyed plugin (plugin$) » — the editor never
 * renders. `dedupe` cannot fix it: the pre-bundle boundary already copied the code.
 *
 * Keeping the whole graph on the source side is the robust direction: a package
 * missed here merely stays source like the rest, whereas the mirror fix
 * (`optimizeDeps.include`) breaks again the moment one is forgotten.
 */
export const playgroundOptimizeExclude = (): string[] => {
  const modules = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../node_modules')
  const list = (dir: string) => {
    try {
      return readdirSync(dir)
    } catch {
      return []
    }
  }

  return [
    ...list(modules).filter((name) => name.startsWith('prosemirror-')),
    ...list(path.join(modules, '@tiptap')).map((name) => `@tiptap/${name}`),
  ]
}
